matrix:
  include:
  - language: python
    python:
    - 3.5.2
    services:
    - mysql
    before_install:
     - cd django_steps/
    install:
     - pip3 install -r requirements.txt
    before_script:
     - mysql -e 'create database stepsdb;'
     - python3 manage.py makemigrations
     - python3 manage.py migrate
    script:
     - python3 manage.py test
  - language: node_js
    node_js:
    - "node"
    script: sh ./scripts/ciTests.sh