# Generated by Django 2.1.1 on 2018-10-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pedestrian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('recorded_time', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('activity_title', models.CharField(max_length=255)),
                ('activity_confidence', models.IntegerField()),
                ('crosswalk', models.BooleanField()),
                ('waiting_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sidewalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('average_overall_rating', models.FloatField()),
                ('average_accessibility_rating', models.FloatField()),
                ('average_comfort_rating', models.FloatField()),
                ('average_connectivity_rating', models.FloatField()),
                ('average_physical_safety_rating', models.FloatField()),
                ('average_sense_of_security', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SidewalkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('sidewalk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sidewalk')),
            ],
        ),
        migrations.CreateModel(
            name='SidewalkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('is_pending', models.BooleanField()),
                ('sidewalk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sidewalk')),
            ],
        ),
        migrations.CreateModel(
            name='SidewalkRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_rating', models.FloatField()),
                ('connectivity_rating', models.FloatField()),
                ('comfort_rating', models.FloatField()),
                ('physical_safety_rating', models.FloatField()),
                ('security_rating', models.FloatField()),
                ('sidewalk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sidewalk')),
            ],
        ),
    ]
