# Generated by Django 2.1.1 on 2018-10-18 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidewalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidewalk_ID', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SidewalkRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibilityRating', models.FloatField()),
                ('connectivityRating', models.FloatField()),
                ('comfortRating', models.FloatField()),
                ('safetyRating', models.FloatField()),
                ('securityRating', models.FloatField()),
                ('sidewalk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sidewalk')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
