# Generated by Django 2.1.1 on 2018-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181029_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidewalkrating',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
