# Generated by Django 2.1.1 on 2018-10-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181018_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pedestrian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=18)),
                ('recorded_time', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('activity_title', models.CharField(max_length=255)),
                ('activity_confidence', models.IntegerField()),
                ('crosswalk', models.BooleanField()),
                ('waiting_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SidewalkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SidewalkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('is_pending', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='SidewalkRatings',
            new_name='SidewalkRating',
        ),
        migrations.RenameField(
            model_name='sidewalkrating',
            old_name='accessibilityRating',
            new_name='accessibility_rating',
        ),
        migrations.RenameField(
            model_name='sidewalkrating',
            old_name='comfortRating',
            new_name='comfort_rating',
        ),
        migrations.RenameField(
            model_name='sidewalkrating',
            old_name='connectivityRating',
            new_name='connectivity_rating',
        ),
        migrations.RenameField(
            model_name='sidewalkrating',
            old_name='safetyRating',
            new_name='physical_safety_rating',
        ),
        migrations.RenameField(
            model_name='sidewalkrating',
            old_name='securityRating',
            new_name='security_rating',
        ),
        migrations.RenameField(
            model_name='sidewalkrating',
            old_name='sidewalk',
            new_name='sidewalk_ID',
        ),
        migrations.RemoveField(
            model_name='sidewalk',
            name='sidewalk_ID',
        ),
        migrations.AddField(
            model_name='sidewalkimage',
            name='sidewalk_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sidewalk'),
        ),
        migrations.AddField(
            model_name='sidewalkcomment',
            name='sidewalk_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sidewalk'),
        ),
    ]
