# Generated by Django 2.1.1 on 2018-11-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sidewalkrating_posted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidewalkrating',
            name='posted_time',
        ),
    ]
