# Generated by Django 2.1.1 on 2018-11-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sidewalkrating_posted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidewalkrating',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
